# Generated by Django 3.1.3 on 2020-12-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_auto_20201220_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixtures_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
