# Generated by Django 3.1.3 on 2020-11-29 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201124_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('trainer', 'trainer'), ('trainee', 'trainee')], default='trainer', max_length=30),
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.CharField(max_length=254)),
                ('guardian_email', models.EmailField(max_length=254, verbose_name="Guardian's Email")),
                ('guardian_name', models.CharField(max_length=254, verbose_name="Guardian's Name")),
                ('guardian_phone_number', models.CharField(max_length=30, verbose_name="Guardian's Phone Number")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=254, null=True, verbose_name="Doctor's Name")),
                ('doctor_phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name="Doctor's Phone Number")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='players/consent-forms/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
