# Generated by Django 3.1.3 on 2020-11-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201129_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/profile-photos/'),
        ),
    ]
