# Generated by Django 3.1.3 on 2020-11-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201129_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consentform',
            name='file',
        ),
        migrations.AddField(
            model_name='consentform',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consentform',
            name='scanned_consent_form',
            field=models.ImageField(null=True, upload_to='players/consent-forms'),
        ),
    ]
