# Generated by Django 3.1.3 on 2020-12-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201224_2207'),
        ('users', '0006_auto_20201227_1541'),
    ]

    operations = [
    ]
