# Generated by Django 3.1.3 on 2021-01-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20201228_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='group',
            field=models.CharField(choices=[('u9', 'Under 9'), ('u12', 'Under 12'), ('u15', 'Under 15'), ('u18', 'Under 18'), ('u21', 'Under 21')], default='u18', max_length=30),
        ),
    ]
