# Generated by Django 3.1.3 on 2021-01-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210106_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
    ]
