# Generated by Django 3.1.3 on 2021-01-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210107_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='fee_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
